language: node_js
node_js:
 - 11.10.1
cache:
  directories:
  - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: gh-pages
before_script:
  - "npm i -g gatsby"
script:
  - "npm run deploy"
